# Generated by Django 5.2.13 on 2026-05-02 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_propertyinterest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_image",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded 2D floor plan (optional if manual override used)",
                        null=True,
                        upload_to="materiaux/plans/",
                    ),
                ),
                ("region", models.CharField(max_length=64)),
                (
                    "gamme",
                    models.CharField(
                        default="moyenne",
                        help_text="bas / moyenne / haute",
                        max_length=16,
                    ),
                ),
                ("budget_tnd", models.DecimalField(decimal_places=2, max_digits=14)),
                ("surface_m2", models.FloatField(blank=True, null=True)),
                (
                    "nb_chambres",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("nb_sdb", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("nb_etages", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "plan_data",
                    models.JSONField(
                        default=dict, help_text="Architectural extraction output"
                    ),
                ),
                (
                    "materiaux",
                    models.JSONField(default=list, help_text="Bill of Quantities list"),
                ),
                (
                    "main_oeuvre",
                    models.JSONField(default=dict, help_text="Labour breakdown"),
                ),
                (
                    "clim_detail",
                    models.JSONField(default=list, help_text="Per-room HVAC sizing"),
                ),
                (
                    "eval_budget",
                    models.JSONField(
                        default=dict, help_text="Budget verdict / ratio / message"
                    ),
                ),
                ("analyse_text", models.TextField(blank=True)),
                ("recommandation_text", models.TextField(blank=True)),
                ("conseil_deco_text", models.TextField(blank=True)),
                (
                    "cout_total_tnd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_estimates",
                        to="core.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_estimates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
