# Generated by Django 5.2.13 on 2026-05-01 21:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_sim", "0002_socialsimrun_user_b"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompatibilityReport",
            fields=[
                (
                    "report_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_a_id", models.CharField(max_length=100)),
                ("subject_b_id", models.CharField(max_length=100)),
                ("property_config", models.JSONField(default=dict)),
                ("compatibility_score", models.FloatField()),
                ("grade", models.CharField(max_length=120)),
                ("full_report", models.JSONField(default=dict)),
                ("lease_checklist", models.JSONField(default=list)),
                ("llm_backend_used", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Compatibility Report",
                "verbose_name_plural": "Compatibility Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NeighborhoodProfileRecord",
            fields=[
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("walkability_score", models.FloatField(default=0.0)),
                ("mobility_score", models.FloatField(default=0.0)),
                ("emergency_score", models.FloatField(default=0.0)),
                ("full_profile", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Neighborhood Profile Record",
                "verbose_name_plural": "Neighborhood Profile Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThermalAssessmentRecord",
            fields=[
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("floor_number", models.IntegerField(default=1)),
                ("orientation", models.CharField(default="unknown", max_length=20)),
                ("building_mass", models.CharField(default="heavy", max_length=20)),
                ("has_cooling", models.BooleanField(default=False)),
                ("has_heating", models.BooleanField(default=False)),
                ("comfort_score", models.FloatField(default=0.0)),
                ("months_comfortable", models.IntegerField(default=0)),
                ("hottest_month_temp", models.FloatField(default=0.0)),
                ("coldest_month_temp", models.FloatField(default=0.0)),
                ("full_report", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Thermal Assessment Record",
                "verbose_name_plural": "Thermal Assessment Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
