# Generated by Django 5.2.13 on 2026-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sim', '0003_compatibilityreport_neighborhoodprofilerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsimrun',
            name='commute_destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialsimrun',
            name='neighbourhood_pois_geo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialsimrun',
            name='noise_sources_geo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialsimrun',
            name='num_ticks',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='socialsimrun',
            name='property_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialsimrun',
            name='property_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialsimrun',
            name='sim_events_partial',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialsimrun',
            name='simulation_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
