# Generated by Django 5.2.13 on 2026-05-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_sim', '0004_socialsimrun_commute_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsimrun',
            name='neighbourhood_profile_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialsimrun',
            name='noise_assessment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialsimrun',
            name='thermal_assessment_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
