"""
Django settings for hestia project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load .env into the process environment before any os.getenv() calls.
# This is required because social_sim modules (ORS, Overpass, Nominatim, etc.)
# read configuration via os.getenv() at class instantiation time.
try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent.parent / ".env", override=False)
except ImportError:
    pass  # python-dotenv not installed; rely on environment variables set externally

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&mym8^==@hcut5s%%e!3g+)ixd$b@4olz^^+hwpusc&ffx(s%s"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "djoser",
    "corsheaders",
    "users",
    "core",
    "room_sim",
    "social_sim",
    "materiaux",
    "appliances",
    "personality",
    "rag_assistant",
]

# Ollama social simulation config
import os
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.2:3b")

# Personality Builder — LLM configuration (TokenFactory / Groq / Ollama)
# Set LLM_BACKEND=tokenfactory and TOKENFACTORY_API_KEY in .env to use TokenFactory.
TOKENFACTORY_API_KEY      = os.environ.get("TOKENFACTORY_API_KEY", "")
TOKENFACTORY_BASE_URL     = os.environ.get("TOKENFACTORY_BASE_URL", "https://tokenfactory.esprit.tn/api")
TOKENFACTORY_PRIMARY_MODEL = os.environ.get("TOKENFACTORY_PRIMARY_MODEL", "hosted_vllm/Llama-3.1-70B-Instruct")
TOKENFACTORY_FAST_MODEL   = os.environ.get("TOKENFACTORY_FAST_MODEL", "hosted_vllm/Llama-3.1-70B-Instruct")
TOKENFACTORY_VERIFY_SSL   = os.environ.get("TOKENFACTORY_VERIFY_SSL", "false")
GROQ_API_KEY              = os.environ.get("GROQ_API_KEY", "")
GROQ_PRIMARY_MODEL        = os.environ.get("GROQ_PRIMARY_MODEL", "llama-3.3-70b-versatile")
GROQ_FAST_MODEL           = os.environ.get("GROQ_FAST_MODEL", "llama-3.1-8b-instant")
LLM_BACKEND               = os.environ.get("LLM_BACKEND", "tokenfactory")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hestia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hestia.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (job artifacts, uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# HorizonNet configuration
CHECKPOINT_PATH = BASE_DIR / "checkpoints" / "horizonnet_resnet50_rnn.pth"
PIPELINE_MAX_WORKERS = 1

# Appliance Energy — CNN checkpoint
APPLIANCE_CNN_PATH = BASE_DIR / "checkpoints" / "mobilenet_best.pth"

# Materiaux — catalog and vector store
MATERIAUX_CATALOG_PATH = BASE_DIR / "materiaux" / "data" / "catalogue_materiaux.json"
MATERIAUX_CHROMA_PATH = BASE_DIR / "chroma_db" / "materiaux_tn"

# Property Wellness Score weights (must sum to 1.0)
WELLNESS_WEIGHTS = {
    "noise":         0.15,
    "neighborhood":  0.15,
    "thermal":       0.15,
    "materiaux":     0.20,
    "appliances":    0.15,
    "compatibility": 0.20,
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "users.CustomUser"

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

# Simple JWT configuration
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),   # extended: polling can take several mins
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}

# Djoser configuration
DJOSER = {
    "USER_ID_FIELD": "id",
    "LOGIN_FIELD": "email",
    "USER_CREATE_PASSWORD_RETYPE": False,
    "ACTIVATION_URL": "auth/activate/{uid}/{token}/",
    "SEND_ACTIVATION_EMAIL": False,
    "SERIALIZERS": {
        "user_create": "users.serializers.CustomUserCreateSerializer",
        "user": "users.serializers.CustomUserSerializer",
        # current_user controls GET/PATCH /auth/users/me/ — must be set explicitly
        "current_user": "users.serializers.CustomUserSerializer",
    },
}

# CORS configuration
# CORS_ALLOW_ALL_ORIGINS=True allows any origin — suitable for local dev & dev tunnels.
# In production, replace with an explicit CORS_ALLOWED_ORIGINS list.
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins for Dev Tunnels
CSRF_TRUSTED_ORIGINS = [
    "https://fjxmjtg3-8081.uks1.devtunnels.ms",
    "http://localhost:5173",
    "http://localhost:8081",
]
if os.environ.get("CSRF_TRUSTED_ORIGINS"):
    CSRF_TRUSTED_ORIGINS.extend(os.environ.get("CSRF_TRUSTED_ORIGINS").split(","))
