# Generated by Django 5.2.13 on 2026-04-27 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReconstructionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("current_step", models.CharField(default="queued", max_length=64)),
                ("align_panorama", models.BooleanField(default=True)),
                ("force_cuboid", models.BooleanField(default=False)),
                ("mesh_stride", models.IntegerField(default=2)),
                ("ignore_ceiling", models.BooleanField(default=True)),
                ("checkpoint_path", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("mesh_vertices", models.IntegerField(blank=True, null=True)),
                ("mesh_faces", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_trace", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
