# Generated by Django 5.2.13 on 2026-05-01 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_propertyinterest"),
        ("room_sim", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconstructionjob",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconstruction_jobs",
                to="core.property",
            ),
        ),
    ]
