# Generated by Django 5.2.13 on 2026-05-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userpersona_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cleanliness",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="daily_schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("early_bird", "Early Bird"),
                    ("flexible", "Flexible"),
                    ("night_owl", "Night Owl"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="noise_tolerance",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="smoker",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="thermal_sensitivity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
