# Generated by Django 5.2.13 on 2026-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_propertyinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='apt_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='building_condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='building_mass',
            field=models.CharField(choices=[('heavy', 'Heavy'), ('medium', 'Medium'), ('light', 'Light')], default='heavy', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_cooling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_internet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='orientation',
            field=models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
