# Generated by Django 5.2.13 on 2026-05-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_apt_configured_property_building_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building_age_years',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='property',
            name='has_cleaning_supplies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_kitchen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_windows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='internet_type',
            field=models.CharField(choices=[('fiber', 'Fiber'), ('adsl', 'ADSL'), ('mobile', 'Mobile'), ('none', 'None'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='property',
            name='natural_light',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='property',
            name='neighbourhood_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='noise_assessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='thermal_assessed',
            field=models.BooleanField(default=False),
        ),
    ]
